"""
CRM Integration Layer
---------------------
This module provides a unified interface for integrating
external CRM systems with ChetnaOS.

Purpose:
- Sync leads generated by AI agents
- Update deal / pipeline status
- Maintain client communication memory
- Enable revenue attribution to agent actions

This layer is intentionally provider-agnostic.
"""

from typing import Dict, Any, Optional
from abc import ABC, abstractmethod


class BaseCRMConnector(ABC):
    """
    Abstract base class for all CRM connectors.
    Every CRM (Zoho, HubSpot, Salesforce, Custom)
    must follow this contract.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    @abstractmethod
    def create_lead(self, lead_data: Dict[str, Any]) -> Dict[str, Any]:
        """Create a new lead in CRM"""
        raise NotImplementedError

    @abstractmethod
    def update_lead(self, lead_id: str, data: Dict[str, Any]) -> bool:
        """Update existing lead"""
        raise NotImplementedError

    @abstractmethod
    def get_lead(self, lead_id: str) -> Dict[str, Any]:
        """Fetch lead details"""
        raise NotImplementedError

    @abstractmethod
    def log_interaction(self, lead_id: str, note: str) -> None:
        """Attach conversation or agent action to lead"""
        raise NotImplementedError


class CRMRegistry:
    """
    Registry for active CRM connector.
    Ensures only ONE CRM is active per client.
    """

    _active_connector: Optional[BaseCRMConnector] = None

    @classmethod
    def register(cls, connector: BaseCRMConnector) -> None:
        cls._active_connector = connector

    @classmethod
    def get(cls) -> BaseCRMConnector:
        if cls._active_connector is None:
            raise RuntimeError("No CRM connector registered")
        return cls._active_connector


__all__ = [
    "BaseCRMConnector",
    "CRMRegistry",
]
